import {Injectable} from '@angular/core';
import {ClothingItem} from '../models/clothing-item.model';
import {ClothingCategory, Color, Gender, Size} from '../models/enums.model';

@Injectable({
  providedIn: 'root',
})
export class ClothingService {
  private items: ClothingItem[] = [];

  constructor() {
    // Eventueel mock data toevoegen bij initialisatie
    this.loadMockData();
  }

  // ✅ Alle items ophalen
  getAllItems(): ClothingItem[] {
    return this.items;
  }

  // ✅ Items per categorie ophalen
  getItemsByCategory(category: ClothingCategory): ClothingItem[] {
    return this.items.filter(item => item.category === category);
  }

  // ✅ Eén item ophalen met ID
  getItemById(id: number): ClothingItem | undefined {
    return this.items.find(item => item.id === id);
  }

  // ✅ Item toevoegen aan lijst
  addItem(item: ClothingItem): void {
    this.items.push(item);
  }

  // (Optioneel) lijst resetten of mock data laden
  private loadMockData(): void {
    this.items = [
      {
        id: 1,
        name: 'Ronde Sticker',
        description: 'kleine ronde sticker!',
        category: ClothingCategory.EXTRA,
        gender: Gender.UNISEX,
        size: [Size.S],
        material: 'Sticker',
        color: [Color.BLACK, Color.WHITE],
        price: 1,
        images: ['assets/merch/products/extra/window-sticker/dens-witte-window-sticker.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 3,
        name: 'Witte Window sticker',
        description: 'Sticker voor auto ruit',
        category: ClothingCategory.EXTRA,
        gender: Gender.UNISEX,
        size: [Size.M],
        material: 'Sticker',
        color: [Color.WHITE],
        price: 15,
        images: ['assets/merch/products/extra/window-sticker/dens-witte-window-sticker.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 5,
        name: 'Dens Beenie',
        description: 'Kwaliteit muts met Dens Logo',
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [Size.M],
        material: '100% Poly Acryl',
        color: [Color.WHITE, Color.BLACK, Color.BEIGE, Color.GREEN, Color.BLUE, Color.DARK_RED, Color.RED, Color.PINK, Color.DARK_BLUE, Color.GRAY],
        price: 25,
        images: ['assets/merch/products/accessory/beanie/dens-beanie.jpg','assets/merch/products/accessory/beanie/dens-2-beanie.jpg', 'assets/merch/products/accessory/beanie/dens-3-beanie.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 6,
        name: '1312 Beenie',
        description: 'Kwaliteit muts met 1312',
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [Size.M],
        material: '100% Poly Acryl',
        color: [Color.WHITE, Color.BLACK, Color.BEIGE, Color.GREEN, Color.BLUE, Color.DARK_RED, Color.RED, Color.PINK, Color.DARK_BLUE, Color.GRAY],
        price: 25,
        images: ['assets/merch/products/accessory/1312-beanie/dens-1312-beanie.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 7,
        name: 'ACAB Beenie',
        description: 'Kwaliteit muts met ACAB',
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [Size.M],
        material: '100% Poly Acryl',
        color: [Color.WHITE, Color.BLACK, Color.BEIGE, Color.GREEN, Color.BLUE, Color.DARK_RED, Color.RED, Color.PINK, Color.DARK_BLUE, Color.GRAY],
        price: 25,
        images: ['assets/merch/products/accessory/acab-beanie/dens-acab-beanie.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 8,
        name: 'Dens Geurhanger',
        description: 'Autogeurhanger met Hugo Boss geur',
        category: ClothingCategory.EXTRA,
        gender: Gender.UNISEX,
        size: [Size.S],
        material: 'Karton',
        color: [Color.WHITE, Color.BLACK],
        price: 2,
        images: ['assets/merch/dens-hoodie-black.png'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 9,
        name: 'Dens Condooms',
        description: "Don't be silly, Wrap your willy",
        category: ClothingCategory.EXTRA,
        gender: Gender.MALE,
        size: [Size.XS],
        material: 'Latex',
        color: [Color.WHITE, Color.BLACK],
        price: 2,
        images: ['assets/merch/products/extra/condoms/dens-condom-3.jpg', 'assets/merch/products/extra/condoms/dens-condom-2.jpg', 'assets/merch/products/extra/condoms/dens-condom.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 10,
        name: 'Dens Energy',
        description: "Geweldige Energy drank, lijkt op redbull maar mlinder bruis en geen plakbek achteraf!",
        category: ClothingCategory.EXTRA,
        gender: Gender.UNISEX,
        size: [Size.CL],
        material: 'Drank',
        color: [Color.WHITE, Color.BLACK],
        price: 3,
        images: ['assets/merch/products/extra/energy/dens-energy.jpg', 'assets/merch/products/extra/energy/dens-2-energy.jpg', 'assets/merch/products/extra/energy/dens-3-energy.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 11,
        name: 'Dens Basic Polo',
        description: "Geweldige Polo van top kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.POLO,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '100% Katoen',
        color: [Color.ANTRACIET_MELANGE, Color.APPLE_GREEN, Color.BORDEAUX, Color.DARK_NAVY, Color.DEEP_ORANGE, Color.DARK_GREEN, Color.GRAY, Color.PINK, Color.BLUE, Color.ARMY_GREEN, Color.YELLOW, Color.TURQUOISE, Color.WHITE, Color.BLACK],
        price: 35,
        images: ['assets/merch/products/polo/dens-perso-polo.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 12,
        name: 'Dens Basic Polo + Quote',
        description: "Geweldige Polo van top kwaliteit met vanvoor Dens Logo en achteraan quote",
        category: ClothingCategory.POLO,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '100% Katoen',
        color: [Color.ANTRACIET_MELANGE, Color.APPLE_GREEN, Color.BORDEAUX, Color.DARK_NAVY, Color.DEEP_ORANGE, Color.DARK_GREEN, Color.GRAY, Color.PINK, Color.BLUE, Color.ARMY_GREEN, Color.YELLOW, Color.TURQUOISE, Color.WHITE, Color.BLACK],
        price: 40,
        images: ['assets/merch/products/polo/dens-quote-polo.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 14,
        name: 'Dens ACAB Polo',
        description: "Geweldige Polo van top kwaliteit met vanvoor Dens Logo en ACAB achteraan",
        category: ClothingCategory.POLO,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '100% Katoen',
        color: [Color.ANTRACIET_MELANGE, Color.APPLE_GREEN, Color.BORDEAUX, Color.DARK_NAVY, Color.DEEP_ORANGE, Color.DARK_GREEN, Color.GRAY, Color.PINK, Color.BLUE, Color.ARMY_GREEN, Color.YELLOW, Color.TURQUOISE, Color.WHITE, Color.BLACK],
        price: 40,
        images: ['assets/merch/products/polo/dens-acab-polo.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 15,
        name: 'Dens 1312 Polo',
        description: "Geweldige Polo van top kwaliteit met vanvoor Dens Logo en 1312 achteraan",
        category: ClothingCategory.POLO,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '100% Katoen',
        color: [Color.ANTRACIET_MELANGE, Color.APPLE_GREEN, Color.BORDEAUX, Color.DARK_NAVY, Color.DEEP_ORANGE, Color.DARK_GREEN, Color.GRAY, Color.PINK, Color.BLUE, Color.ARMY_GREEN, Color.YELLOW, Color.TURQUOISE, Color.WHITE, Color.BLACK],
        price: 40,
        images: ['assets/merch/products/polo/dens-1312-polo.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 16,
        name: 'Dens Perso Polo',
        description: "Geweldige Polo van top kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.POLO,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '100% Katoen',
        color: [Color.ANTRACIET_MELANGE, Color.APPLE_GREEN, Color.BORDEAUX, Color.DARK_NAVY, Color.DEEP_ORANGE, Color.DARK_GREEN, Color.GRAY, Color.PINK, Color.BLUE, Color.ARMY_GREEN, Color.YELLOW, Color.TURQUOISE, Color.WHITE, Color.BLACK],
        price: 35,
        images: ['assets/merch/products/polo/dens-perso-polo.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 17,
        name: 'Basic Dens Hoodie',
        description: "Geweldige Hoodie van ok kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '270 gram, 50% Katoen, 50% Polyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 35,
        images: ['assets/merch/products/hoodies/classic/dens-premium-classic-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 18,
        name: 'Basic Dens Hoodie + Quote',
        description: "Geweldige Hoodie van ok kwaliteit met vanvoor Dens Logo en achteraan quote",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '270 gram, 50% Katoen, 50% Polyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 40,
        images: ['assets/merch/products/hoodies/perso/dens-premium-perso-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-2-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-3-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 19,
        name: 'Basic Dens Hoodie Deluxe',
        description: "Geweldige Hoodie van ok kwaliteit met vanvoor Dens Logo en achteraan quote",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '270 gram, 50% Katoen, 50% Polyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 40,
        images: ['assets/merch/products/hoodies/classic/dens-premium-classic-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 20,
        name: 'Dens ACAB Hoodie',
        description: "Geweldige Hoodie van ok kwaliteit met vanvoor Dens Logo en ACAB achteraan",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '270 gram, 50% Katoen, 50% Polyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 40,
        images: ['assets/merch/products/hoodies/acab/dens-premium-acab-2-hoodie.jpg','assets/merch/products/hoodies/acab/dens-premium-acab-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 21,
        name: 'Dens 1312 Hoodie',
        description: "Geweldige Hoodie van ok kwaliteit met vanvoor Dens Logo en 1312 achteraan",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '270 gram, 50% Katoen, 50% Polyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 40,
        images: ['assets/merch/products/hoodies/1312/dens-premium-1312-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 22,
        name: 'Dens Perso Hoodie',
        description: "Geweldige Hoodie van ok kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '270 gram, 50% Katoen, 50% Polyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 35,
        images: ['assets/merch/products/hoodies/perso/dens-premium-perso-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-2-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-3-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 23,
        name: 'Dens Premium Hoodie',
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '280 gram, 70% biologisch katoen, 30% plyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 50,
        images: ['assets/merch/products/hoodies/classic/dens-premium-classic-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 24,
        name: 'Dens Premium Hoodie + Quote',
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo en achteraan quote",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '280 gram, 70% biologisch katoen, 30% plyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 55,
        images: ['assets/merch/products/hoodies/perso/dens-premium-perso-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-2-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-3-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 25,
        name: 'Dens Premium Hoodie Deluxe',
        description: "Geweldige Hoodie van top kwaliteit met vanvoor en achteraan Dens Logo",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '280 gram, 70% biologisch katoen, 30% plyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 55,
        images: ['assets/merch/products/hoodies/classic/dens-premium-classic-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 26,
        name: 'Dens Premium ACAB Hoodie',
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo en ACAB achteraan",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '280 gram, 70% biologisch katoen, 30% plyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 55,
        images: ['assets/merch/products/hoodies/acab/dens-premium-acab-2-hoodie.jpg','assets/merch/products/hoodies/acab/dens-premium-acab-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 27,
        name: 'Dens Premium 1312 Hoodie',
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo en 1312 achteraan",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '280 gram, 70% biologisch katoen, 30% plyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 55,
        images: ['assets/merch/products/hoodies/1312/dens-premium-1312-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 28,
        name: 'Dens Premium Perso Hoodie',
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo en 1312 achteraan",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL],
        material: '280 gram, 70% biologisch katoen, 30% plyester',
        color: [Color.ANTRACIET_MELANGE, Color.BLACK, Color.DARK_GREEN, Color.BROWN, Color.BURGUNDY, Color.GRAY, Color.NAVY, Color.ORANGE, Color.RED, Color.BLUE, Color.WHITE],
        price: 50,
        images: ['assets/merch/products/hoodies/classic/dens-premium-classic-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 29,
        name: 'Dens Premium Heavy Hoodie',
        description: "Geweldige zware Hoodie van top kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL, Size.XXXXXL],
        material: '500 gram, fleeze binnenkant, 80% katoen, 20% polyester',
        color: [Color.BLACK],
        price: 90,
        images: ['assets/merch/products/hoodies/classic/dens-premium-classic-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 30,
        name: 'Dens Premium Heavy Hoodie + Quote',
        description: "Geweldige zware Hoodie van top kwaliteit met vanvoor Dens Logo en achteraan quote",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL, Size.XXXXXL],
        material: '500 gram, fleeze binnenkant, 80% katoen, 20% polyester',
        color: [Color.BLACK],
        price: 100,
        images: ['assets/merch/products/hoodies/perso/dens-premium-perso-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-2-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-3-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 31,
        name: 'Dens Premium Heavy Hoodie Deluxe',
        description: "Geweldige zware Hoodie van top kwaliteit met vanvoor en achteraan Dens Logo",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL, Size.XXXXXL],
        material: '500 gram, fleeze binnenkant, 80% katoen, 20% polyester',
        color: [Color.BLACK],
        price: 100,
        images: ['assets/merch/products/hoodies/classic/dens-premium-classic-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 32,
        name: 'Dens Premium Heavy ACAB Hoodie',
        description: "Geweldige zware Hoodie van top kwaliteit met vanvoor Dens Logo en ACAB achteraan",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL, Size.XXXXXL],
        material: '500 gram, fleeze binnenkant, 80% katoen, 20% polyester',
        color: [Color.BLACK],
        price: 100,
        images: ['assets/merch/products/hoodies/acab/dens-premium-acab-2-hoodie.jpg','assets/merch/products/hoodies/acab/dens-premium-acab-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 33,
        name: 'Dens Premium Heavy 1312 Hoodie',
        description: "Geweldige zware Hoodie van top kwaliteit met vanvoor Dens Logo en 1312 achteraan",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL, Size.XXXXXL],
        material: '500 gram, fleeze binnenkant, 80% katoen, 20% polyester',
        color: [Color.BLACK],
        price: 100,
        images: ['assets/merch/products/hoodies/1312/dens-premium-1312-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 34,
        name: 'Dens Premium Heavy Perso Hoodie',
        description: "Geweldige zware Hoodie van top kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.HOODIE,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL, Size.XXXXL, Size.XXXXXL],
        material: '500 gram, fleeze binnenkant, 80% katoen, 20% polyester',
        color: [Color.BLACK],
        price: 100,
        images: ['assets/merch/products/hoodies/perso/dens-premium-perso-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-2-hoodie.jpg', 'assets/merch/products/hoodies/perso/dens-premium-perso-3-hoodie.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 35,
        name: 'Dens Premium T-Shirt',
        description: "Premium tshirt met lichte oversized fit, past perfect op fitte bodies en dad bods, amazing fit",
        category: ClothingCategory.TSHIRT,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL],
        material: '190 gram, 100% katoen',
        color: [Color.BLACK, Color.WHITE],
        price: 35,
        images: ['assets/merch/products/t-shirt/classic/dens-premium-3-t-shirt.jpg', 'assets/merch/products/t-shirt/classic/dens-premium-t-shirt.jpg', 'assets/merch/products/t-shirt/classic/dens-premium-2-t-shirt.jpg', 'assets/merch/products/t-shirt/classic/dens-t-shirt.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 36,
        name: 'Dens Premium ACAB T-Shirt',
        description: "Premium tshirt met lichte oversized fit, past perfect op fitte bodies en dad bods, amazing fit",
        category: ClothingCategory.TSHIRT,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL],
        material: '190 gram, 100% katoen',
        color: [Color.BLACK, Color.WHITE],
        price: 40,
        images: ['assets/merch/products/t-shirt/acab/dens-acab-t-shirt.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 37,
        name: 'Dens Premium 1312 T-Shirt',
        description: "Premium tshirt met lichte oversized fit, past perfect op fitte bodies en dad bods, amazing fit",
        category: ClothingCategory.TSHIRT,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL],
        material: '190 gram, 100% katoen',
        color: [Color.BLACK, Color.WHITE],
        price: 40,
        images: ['assets/merch/products/t-shirt/1312/dens-1312-t-shirt.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 38,
        name: 'Dens Premium Afraid of women T-Shirt',
        description: "Premium tshirt met lichte oversized fit, past perfect op fitte bodies en dad bods, amazing fit",
        category: ClothingCategory.TSHIRT,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL],
        material: '190 gram, 100% katoen',
        color: [Color.BLACK, Color.WHITE],
        price: 40,
        images: [ 'assets/merch/products/t-shirt/afraid-of-woman/dens-premium-afraid-of-woman-4-t-shirt.jpg', 'assets/merch/products/t-shirt/afraid-of-woman/dens-premium-afraid-of-woman-1-t-shirt.jpg', 'assets/merch/products/t-shirt/afraid-of-woman/dens-premium-afraid-of-woman-2-t-shirt.jpg', 'assets/merch/products/t-shirt/afraid-of-woman/dens-premium-afraid-of-woman-3-t-shirt.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 39,
        name: 'Dens Premium I tren everyday T-shirt',
        description: "Premium tshirt met lichte oversized fit, past perfect op fitte bodies en dad bods, amazing fit",
        category: ClothingCategory.TSHIRT,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL],
        material: '190 gram, 100% katoen',
        color: [Color.BLACK, Color.WHITE],
        price: 40,
        images: ['assets/merch/products/t-shirt/i-tren-everyday/dens-premium-i-tren-everyday-t-shirt.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 40,
        name: "Dens Premium Dead pedophiles don't reoffend T-shirt",
        description: "Premium tshirt met lichte oversized fit, past perfect op fitte bodies en dad bods, amazing fit",
        category: ClothingCategory.TSHIRT,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL],
        material: '190 gram, 100% katoen',
        color: [Color.BLACK, Color.WHITE],
        price: 45,
        images: ['assets/merch/products/t-shirt/dead-pedophile-dont-reoffend/dens-premium-dead-pedophiles-dont-reoffend-t-shirt.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 41,
        name: "Dens Premium perso T-shirt",
        description: "Premium tshirt met lichte oversized fit, past perfect op fitte bodies en dad bods, amazing fit",
        category: ClothingCategory.TSHIRT,
        gender: Gender.UNISEX,
        size: [Size.XS, Size.S, Size.M, Size.L, Size.XL, Size.XXL],
        material: '190 gram, 100% katoen',
        color: [Color.BLACK, Color.WHITE],
        price: 35,
        images: ['assets/merch/products/t-shirt/perso/dens-perso-t-shirt.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: ["DM Instagram"],
          textColors: ["DM Instagram"],
          textLocations: ["DM Instagram"],
          extraCost: 5,
        }
      },
      {
        id: 42,
        name: "Dens Pet",
        description: "Top autentiek 5 panelen pet met of zonder gaas",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% Katoen (zonder gaas) / 100% gevoerd Polyester (met gaas)',
        color: [Color.BLACK, Color.DARK_GREEN, Color.BLUE, Color.BORDEAUX, Color.WHITE, Color.RED, Color.NAVY, Color.GRAY],
        price: 25,
        images: ['assets/merch/products/accessory/pet/dens-pet.jpg', 'assets/merch/products/pet/dens-2-pet.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 43,
        name: "Dens ACAB Pet",
        description: "Top pet met of zonder gaas. (Gaas is gekleurd, paneel is altjd wit met zwart logo / tekst)",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% Katoen (zonder gaas) / 100% gevoerd Polyester (met gaas)',
        color: [Color.BLACK, Color.DARK_GREEN, Color.NAVY, Color.PURPLE, Color.RED, Color.PINK],
        price: 25,
        images: ['assets/merch/products/accessory/pet/dens-acab-pet.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 44,
        name: "Dens 1312 Pet",
        description: "Top pet met of zonder gaas. (Gaas is gekleurd, paneel is altjd wit met zwart logo / tekst)",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% Katoen (zonder gaas) / 100% gevoerd Polyester (met gaas)',
        color: [Color.BLACK, Color.DARK_GREEN, Color.NAVY, Color.PURPLE, Color.RED, Color.PINK],
        price: 25,
        images: ['assets/merch/products/accessory/pet/dens-1312-pet.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 45,
        name: "Dens Visser hoedje",
        description: "Leuk visserhoedje van topkwaliteit",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% biologisch katoen',
        color: [Color.BLACK, Color.NAVY, Color.GRAY, Color.BEIGE],
        price: 25,
        images: ['assets/merch/products/accessory/vissershoedje/dens-classic-vissershoed.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 46,
        name: "Dens ACAB Visser hoedje",
        description: "Leuk visserhoedje van topkwaliteit",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% biologisch katoen',
        color: [Color.BLACK, Color.NAVY, Color.GRAY, Color.BEIGE],
        price: 25,
        images: ['assets/merch/products/accessory/vissershoedje/dens-acab-vissershoed.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 47,
        name: "Dens 1312 Visser hoedje",
        description: "Leuk visserhoedje van topkwaliteit",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% biologisch katoen',
        color: [Color.BLACK, Color.NAVY, Color.GRAY, Color.BEIGE],
        price: 25,
        images: ['assets/merch/products/accessory/vissershoedje/dens-1312-vissershoed.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 48,
        name: "Dens Army Cap",
        description: "Stoere legerstijl pet van topkwaliteit",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% zwaar gewassen katoen',
        color: [Color.BLACK, Color.NAVY, Color.GRAY, Color.BEIGE, Color.DARK_GREEN, Color.KHAKI],
        price: 25,
        images: ['assets/merch/products/accessory/army-cap/dens-classic-army-cap.jpg', 'assets/merch/products/accessory/army-cap/dens-model-army-cap.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 49,
        name: "Dens ACAB Army Cap",
        description: "Stoere legerstijl pet van topkwaliteit",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% zwaar gewassen katoen',
        color: [Color.BLACK, Color.NAVY, Color.GRAY, Color.BEIGE, Color.DARK_GREEN, Color.KHAKI],
        price: 25,
        images: ['assets/merch/products/accessory/army-cap/dens-acab-army-cap.jpg', 'assets/merch/products/accessory/army-cap/dens-model-army-cap.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 50,
        name: "Dens 1312 Army Cap",
        description: "Stoere legerstijl pet van topkwaliteit",
        category: ClothingCategory.ACCESSORY,
        gender: Gender.UNISEX,
        size: [],
        material: '100% zwaar gewassen katoen',
        color: [Color.BLACK, Color.NAVY, Color.GRAY, Color.BEIGE, Color.DARK_GREEN, Color.KHAKI],
        price: 25,
        images: ['assets/merch/products/accessory/army-cap/dens-1312-army-cap.jpg', 'assets/merch/products/accessory/army-cap/dens-model-army-cap.jpg'],
        personalizationAllowed: false,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 51,
        name: "Dens Jas",
        description: "Geweldige Jas van top kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '300gram Buitenkant, 92% polyester, 8% Spandex // Binnenkant 100% Polyester met extra warmte laag',
        color: [Color.BLACK, Color.WHITE, Color.DARK_GREEN, Color.NAVY, Color.RED, Color.BLUE],
        price: 55,
        images: ['assets/merch/products/jacket/jas/dens-jas.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 52,
        name: "Dens Deluxe Jas",
        description: "Geweldige Jas van top kwaliteit met vanvoor Dens Logo en achteraan quote",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '300gram Buitenkant, 92% polyester, 8% Spandex // Binnenkant 100% Polyester met extra warmte laag',
        color: [Color.BLACK, Color.WHITE, Color.DARK_GREEN, Color.NAVY, Color.RED, Color.BLUE],
        price: 60,
        images: ['assets/merch/products/jacket/jas/dens-jas.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 53,
        name: "Dens Dubbel Jas",
        description: "Geweldige Jas van top kwaliteit met vanvoor Dens Logo en achteraan quote",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '300gram Buitenkant, 92% polyester, 8% Spandex // Binnenkant 100% Polyester met extra warmte laag',
        color: [Color.BLACK, Color.WHITE, Color.DARK_GREEN, Color.NAVY, Color.RED, Color.BLUE],
        price: 60,
        images: ['assets/merch/products/jacket/jas/dens-perso-jas.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 54,
        name: "Dens ACAB Jas",
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo en ACAB achteraan",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '300gram Buitenkant, 92% polyester, 8% Spandex // Binnenkant 100% Polyester met extra warmte laag',
        color: [Color.BLACK, Color.WHITE, Color.DARK_GREEN, Color.NAVY, Color.RED, Color.BLUE],
        price: 60,
        images: ['assets/merch/products/jacket/jas/dens-acab-jas.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 55,
        name: "Dens 1312 Jas",
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo en 1312 achteraan",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '300gram Buitenkant, 92% polyester, 8% Spandex // Binnenkant 100% Polyester met extra warmte laag',
        color: [Color.BLACK, Color.WHITE, Color.DARK_GREEN, Color.NAVY, Color.RED, Color.BLUE],
        price: 60,
        images: ['assets/merch/products/jacket/jas/dens-1312-jas.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 56,
        name: "Dens Perso Jas",
        description: "Geweldige Hoodie van top kwaliteit met vanvoor Dens Logo",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '300gram Buitenkant, 92% polyester, 8% Spandex // Binnenkant 100% Polyester met extra warmte laag',
        color: [Color.BLACK, Color.WHITE, Color.DARK_GREEN, Color.NAVY, Color.RED, Color.BLUE],
        price: 55,
        images: ['assets/merch/products/jacket/jas/dens-jas.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 57,
        name: "Dens Regenjasje",
        description: "Windbreaker perfect voor regenachtige dagen op circuit of dergelijke, volledig water en wind dicht",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '100% Nylon Taffeta',
        color: [Color.BLACK, Color.WHITE, Color.BLUE, Color.DARK_GREEN, Color.ORANGE, Color.DARK_BLUE, Color.PURPLE, Color.PINK, Color.GREEN, Color.BORDEAUX, Color.BRIGHT_ORANGE],
        price: 30,
        images: ['assets/merch/products/jacket/regenjas/dens-regenjasje.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 58,
        name: "Dens Deluxe Regenjasje",
        description: "Windbreaker perfect voor regenachtige dagen op circuit of dergelijke, volledig water en wind dicht",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '100% Nylon Taffeta',
        color: [Color.BLACK, Color.WHITE, Color.BLUE, Color.DARK_GREEN, Color.ORANGE, Color.DARK_BLUE, Color.PURPLE, Color.PINK, Color.GREEN, Color.BORDEAUX, Color.BRIGHT_ORANGE],
        price: 35,
        images: ['assets/merch/products/jacket/regenjas/dens-regenjasje.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 59,
        name: "Dens Dubbel Regenjasje",
        description: "Windbreaker perfect voor regenachtige dagen op circuit of dergelijke, volledig water en wind dicht",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '100% Nylon Taffeta',
        color: [Color.BLACK, Color.WHITE, Color.BLUE, Color.DARK_GREEN, Color.ORANGE, Color.DARK_BLUE, Color.PURPLE, Color.PINK, Color.GREEN, Color.BORDEAUX, Color.BRIGHT_ORANGE],
        price: 35,
        images: ['assets/merch/products/jacket/regenjas/dens-regenjasje.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 60,
        name: "Dens ACAB Regenjasje",
        description: "Windbreaker perfect voor regenachtige dagen op circuit of dergelijke, volledig water en wind dicht met ACAB achterop",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '100% Nylon Taffeta',
        color: [Color.BLACK, Color.WHITE, Color.BLUE, Color.DARK_GREEN, Color.ORANGE, Color.DARK_BLUE, Color.PURPLE, Color.PINK, Color.GREEN, Color.BORDEAUX, Color.BRIGHT_ORANGE],
        price: 35,
        images: ['assets/merch/products/jacket/regenjas/dens-acab-regenjasje.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 61,
        name: "Dens 1312 Regenjasje",
        description: "Windbreaker perfect voor regenachtige dagen op circuit of dergelijke, volledig water en wind dicht met 1312 achterop",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '100% Nylon Taffeta',
        color: [Color.BLACK, Color.WHITE, Color.BLUE, Color.DARK_GREEN, Color.ORANGE, Color.DARK_BLUE, Color.PURPLE, Color.PINK, Color.GREEN, Color.BORDEAUX, Color.BRIGHT_ORANGE],
        price: 35,
        images: ['assets/merch/products/jacket/regenjas/dens-1312-regenjasje.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
      {
        id: 62,
        name: "Dens Perso Regenjasje",
        description: "Windbreaker perfect voor regenachtige dagen op circuit of dergelijke, volledig water en wind dicht met 1312 achterop",
        category: ClothingCategory.JACKET,
        gender: Gender.UNISEX,
        size: [Size.S, Size.M, Size.L, Size.XL, Size.XXL, Size.XXXL],
        material: '100% Nylon Taffeta',
        color: [Color.BLACK, Color.WHITE, Color.BLUE, Color.DARK_GREEN, Color.ORANGE, Color.DARK_BLUE, Color.PURPLE, Color.PINK, Color.GREEN, Color.BORDEAUX, Color.BRIGHT_ORANGE],
        price: 30,
        images: ['assets/merch/products/jacket/regenjas/dens-regenjasje.jpg', 'assets/merch/products/regenjas/dens-perso-regenjasje.jpg'],
        personalizationAllowed: true,
        personalizationOptions: {
          maxTextLength: 0,
          availableFonts: [],
          textColors: [],
          textLocations: [],
          extraCost: 0,
        }
      },
    ];
  }
}
